clc;
clear;
close;

N = 41;
M = (N-1)/2;
k = 0:M;
w = k*2*pi/N;
Ak = 1*(w>=pi/3 & w<=2*pi/3);

hn = (Ak(1) + sum(2*Ak(2:end)'.*cos(2*pi*((0:N-1)-M).*k(2:end)'/N),1))/N;
omega = linspace(0,2*pi,1e3);
H = sum(hn'.*exp(-1i*(0:N-1)'.*omega),1);
figure(1);
stem((0:N-1),hn,'.');
title('h[n]');
xlabel('n');
ylabel('h[n]');
figure(2);
subplot(2,1,1);
stem(w,Ak,'.');
hold on;
plot(omega,abs(H));
title('A_k and |H(e^{j\omega})|, no transition point');
xlabel('\omega');
ylabel('|H(e^{j\omega})|');
xlim([0,2*pi]);
legend('A_k', '|H(e^{j\omega})|');
set(gca,'XTick',0:pi/3:2*pi);
set(gca,'XTickLabel',{'0','\pi/3','2\pi/3','\pi','4\pi/3','5\pi/3','2\pi'});
subplot(2,1,2);
plot(omega,angle(H));
title('\angleH(e^{j\omega}), no transition point');
xlabel('\omega');
ylabel('\angleH(e^{j\omega})');
xlim([0,2*pi]);
set(gca,'XTick',0:pi/3:2*pi);
set(gca,'XTickLabel',{'0','\pi/3','2\pi/3','\pi','4\pi/3','5\pi/3','2\pi'});

Ak(find(w<pi/3,1,"last")) = 0.3904;
Ak(find(w>2*pi/3,1,"first")) = 0.3904;
hn = (Ak(1) + sum(2*Ak(2:end)'.*cos(2*pi*((0:N-1)-M).*k(2:end)'/N),1))/N;
H = sum(hn'.*exp(-1i*(0:N-1)'.*omega),1);
figure(3);
stem((0:N-1),hn,'.');
title('h[n]');
xlabel('n');
ylabel('h[n]');
figure(4);
subplot(2,1,1);
stem(w,Ak,'.');
hold on;
plot(omega,abs(H));
title('A_k and |H(e^{j\omega})|, with one transition point');
xlabel('\omega');
ylabel('|H(e^{j\omega})|');
xlim([0,2*pi]);
legend('A_k', '|H(e^{j\omega})|');
set(gca,'XTick',0:pi/3:2*pi);
set(gca,'XTickLabel',{'0','\pi/3','2\pi/3','\pi','4\pi/3','5\pi/3','2\pi'});
subplot(2,1,2)
plot(omega,angle(H));
title('\angleH(e^{j\omega}), with one transition point');
xlabel('\omega');
ylabel('\angleH(e^{j\omega})');
xlim([0,2*pi]);
set(gca,'XTick',0:pi/3:2*pi);
set(gca,'XTickLabel',{'0','\pi/3','2\pi/3','\pi','4\pi/3','5\pi/3','2\pi'});

Ak(find(w<pi/3,2,"last")) = [1/4 3/4];
Ak(find(w>2*pi/3,2,"first")) = [3/4 1/4];
hn = (Ak(1) + sum(2*Ak(2:end)'.*cos(2*pi*((0:N-1)-M).*k(2:end)'/N),1))/N;
H = sum(hn'.*exp(-1i*(0:N-1)'.*omega),1);
figure(5);
stem((0:N-1),hn,'.');
title('h[n]');
xlabel('n');
ylabel('h[n]');
figure(6);
subplot(2,1,1);
stem(w,Ak,'.');
hold on;
plot(omega,abs(H));
title('A_k and |H(e^{j\omega})|, with one transition point');
xlabel('\omega');
ylabel('|H(e^{j\omega})|');
xlim([0,2*pi]);
legend('A_k', '|H(e^{j\omega})|');
set(gca,'XTick',0:pi/3:2*pi);
set(gca,'XTickLabel',{'0','\pi/3','2\pi/3','\pi','4\pi/3','5\pi/3','2\pi'});
subplot(2,1,2);
plot(omega,angle(H));
title('\angleH(e^{j\omega}), N=41 with two transition points');
xlabel('\omega');
ylabel('\angleH(e^{j\omega})');
xlim([0,2*pi]);
set(gca,'XTick',0:pi/3:2*pi);
set(gca,'XTickLabel',{'0','\pi/3','2\pi/3','\pi','4\pi/3','5\pi/3','2\pi'});