clc;
clear;
close;

T = 0.1;
N = 32;
n = (0:N-1)';
hn = cos(2*pi*n*T*1.1) + 0.07*cos(2*pi*n*T*2.9);
fs = 1/T;
N_fft = 1024;
f = (-N_fft/2:N_fft/2-1)*fs/N_fft;
w_r = rectwin(N);
H = fft(hn.*w_r);
figure(1);
stem(n,abs(H),'.');
title('Amplitude of H[k]');
xlabel('k'); ylabel('|H[k]|');
figure(2);
plot(f,abs(fftshift(fft(hn.*w_r,N_fft))));
title('Amplitude of H[k]');
xlabel('f'); ylabel('|H[k]|');

w_hm = hamming(N);
figure(3);
subplot(2,2,1);
stem(n,hn,'.');
title('h[n]');
xlabel('n'); ylabel('h[n]');
subplot(2,2,2);
stem(n,w_hm,'.');
title('w_{hm}[n]');
xlabel('n'); ylabel('w_{hm}[n]');
subplot(2,2,3:4);
stem(n,hn.*w_hm,'.');
title('h[n]w_{hm}[n]');
xlabel('n'); ylabel('h[n]w_{hm}[n]');
H = fft(hn.*w_hm);
figure(4);
stem(n,abs(H),'.');
title('Amplitude of H[k]');
xlabel('k'); ylabel('|H[k]|');
figure(5);
plot(f,abs(fftshift(fft(hn.*w_hm,N_fft))));
title('Amplitude of H[k]');
xlabel('f'); ylabel('|H[k]|');

w_b = blackman(N);
figure(6);
subplot(2,2,1);
stem(n,hn,'.');
title('h[n]');
xlabel('n'); ylabel('h[n]');
subplot(2,2,2);
stem(n,w_b,'.');
title('w_b[n]');
xlabel('n'); ylabel('w_b[n]');
subplot(2,2,3:4);
stem(n,hn.*w_b,'.');
title('h[n]w_b[n]');
xlabel('n'); ylabel('h[n]w_b[n]');
H = fft(hn.*w_b);
figure(7);
stem(n,abs(H),'.');
title('Amplitude of H[k]');
xlabel('k'); ylabel('|H[k]|');
figure(8);
plot(f,abs(fftshift(fft(hn.*w_b,N_fft))));
title('Amplitude of H[k]');
xlabel('f'); ylabel('|H[k]|');